language: python

python:
  - "2.7"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

install:
  - python setup.py develop
  - pip install tox
script: tox -e $TOXENV
notifications:
  email: false
env:
  - TOXENV=py27
  - TOXENV=nightly
  - TOXENV=pypy
